#!/bin/bash
if [ $# -ne 1 ]; then
    echo "command should be formatted as 'toggle_led <gpio-pin>'"
    exit 1
fi

LED=$1
# verify that the gpio pin is valid.

# check whether the led is active
function check_led(){
    cd /sys/class/gpio
    if [[ " ${arr[@]} " =~ " ${value} " ]]; then
        return 1
    else
        return 0
    fi
}
# setup the led if it has not been setup yet   
if [ check_led -eq 0]; then
    cd /sys/class/gpio
    echo $LED > export
    cd gpio$LED
    echo "out" > direction
else
    cd /sys/class/gpio/gpio$LED
    echo "out" > direction
fi

# check the value of the led and toggle
status = $(cat value)
if [ "$status" -eq "0"] then
    echo "1" > value
else
    echo "0" > value
fi
